steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/authority-discovery', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/authority-discovery']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'authority-discovery'
      - '--image'
      - 'gcr.io/$PROJECT_ID/authority-discovery'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DATABASE_URL=$$DATABASE_URL,ANTHROPIC_API_KEY=$$ANTHROPIC_API_KEY'
images:
  - 'gcr.io/$PROJECT_ID/authority-discovery'
